### ISSUE TITLE
missing sorting indicator

### ISSUE THREAD

**Issue by m-e-h** [gravityflow/gravityflow#10]
Not sure if you've included styles for the front-end `.sorting-indacator` but I'm not seeing any in devtools.

![gf-sort](https://cloud.githubusercontent.com/assets/3585901/22989481/0b5e21f6-f384-11e6-8717-ca2e2a2b2a80.png)

I've added my own for now 
```css
.sorting-indicator {
    background-image: url("data:image/svg+xml, %3Csvg xmlns='http://www.w3.org/2000/svg' fill='%23555' viewBox='0 0 24 24'%3E%3Cpath d='M7 10.385L12.25 5l5.25 5.385zm0 3.23L12.25 19l5.25-5.385z'/%3E%3C/svg%3E");
	width: 1.1rem;
    height: 1.1rem;
    display: inline-block;
    vertical-align: middle;
}
```

but I'll remove them if they should already be there.
